### ISSUE TITLE
Signature validation fails when re-read data from disk

### ISSUE THREAD

**Issue by Menooker** [tomp2p/TomP2P#107]
I put some data in DHT (disk storage based) by 
new Data(obj).protectEntryNow(key,factory).sign(key.getPrivate())

obj is a large object with the size of about 20k.
Then I got the data immediately after putting it and every thing went well.

But when I closed the peer and restarted the whole DHT and tried to read the value 'obj' I put before, an exception is raised when calling data.verify():
java.security.SignatureException: invalid signature: out of range values
	at sun.security.provider.DSA.engineVerify(Unknown Source)
	at sun.security.provider.DSA.engineVerify(Unknown Source)
	at java.security.Signature$Delegate.engineVerify(Unknown Source)
	at java.security.Signature.verify(Unknown Source)
	at net.tomp2p.connection.DSASignatureFactory.verify(DSASignatureFactory.java:133)
	at net.tomp2p.storage.Data.verify(Data.java:376)

And I find that small objects are okay but this problem emerges when the object stored is large. (>20k)

**Comment by Menooker** [comment]
Since the problem only occurs when the signed data is read from the disk, there may be something wrong with the file related codes.
