### ISSUE TITLE
ExampleDNS.java fails out of box

### ISSUE THREAD

**Issue by tchoulihan** [tomp2p/TomP2P#88]
[Here's](https://github.com/tomp2p/TomP2P/blob/master/examples/src/main/java/net/tomp2p/examples/ExampleDNS.java) the file I'm testing. It compiles with maven correctly, and the server appears to start up fine, but the client node throws a NoSuchElementException:

Here's the console output:
```
21:56:55.488 [main] INFO  net.tomp2p.connection.PeerCreator - Status of external search: Discover status:  ++wlan0( /192.168.1.147), ++lo( /127.0.0.1).
21:56:55.500 [main] INFO  net.tomp2p.connection.PeerCreator - Visible address to other peers: paddr[0xbb2c72394b1ab9f8e6c5459001105f177f2fc3ea[/192.168.1.147,4002]]/relay(false)/slow(false)
21:56:55.520 [main] DEBUG i.n.u.i.l.InternalLoggerFactory - Using SLF4J as the default logging framework
21:56:55.528 [main] DEBUG i.n.c.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 4
21:56:55.567 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
21:56:55.574 [main] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
21:56:55.575 [main] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
21:56:55.580 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: true
21:56:55.584 [main] DEBUG i.n.util.internal.PlatformDependent - Java version: 8
21:56:55.585 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noUnsafe: false
21:56:55.586 [main] DEBUG i.n.util.internal.PlatformDependent - sun.misc.Unsafe: available
21:56:55.596 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noJavassist: false
21:56:55.599 [main] DEBUG i.n.util.internal.PlatformDependent - Javassist: unavailable
21:56:55.602 [main] DEBUG i.n.util.internal.PlatformDependent - You don't have Javassist in your class path or you don't have enough permission to load dynamically generated classes.  Please check the configuration for better performance.
21:56:55.603 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
21:56:55.605 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
21:56:55.606 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
21:56:55.711 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
21:56:55.712 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
21:56:55.887 [pool-1-thread-1] DEBUG i.n.util.internal.ThreadLocalRandom - -Dio.netty.initialSeedUniquifier: 0x0d368e95bc48b88f (took 33 ms)
21:56:55.962 [pool-1-thread-1] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: unpooled
21:56:55.963 [pool-1-thread-1] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 65536
21:56:56.121 [NETTY-TOMP2P - worker-client/server - -1-1] DEBUG i.n.util.internal.PlatformDependent - UID: 1000
21:56:56.290 [pool-1-thread-1] INFO  net.tomp2p.connection.ChannelServer - Listening on broadcast address: /192.168.1.255:4002 on port udp: 4002
21:56:56.302 [pool-1-thread-1] DEBUG io.netty.util.NetUtil - Loopback interface: lo (lo, 127.0.0.1)
21:56:56.303 [pool-1-thread-1] DEBUG io.netty.util.NetUtil - /proc/sys/net/core/somaxconn: 128
21:56:56.307 [pool-1-thread-1] INFO  net.tomp2p.connection.ChannelServer - Listening on address: /192.168.1.147 on port tcp: 4002
21:56:56.310 [pool-1-thread-1] INFO  net.tomp2p.connection.ChannelServer - Listening on address: /192.168.1.147 on port udp: 4002
21:56:56.314 [pool-1-thread-1] INFO  net.tomp2p.connection.ChannelServer - Listening on address: /127.0.0.1 on port tcp: 4002
21:56:56.319 [pool-1-thread-1] INFO  net.tomp2p.connection.ChannelServer - Listening on address: /127.0.0.1 on port udp: 4002
21:56:56.413 [main] DEBUG net.tomp2p.rpc.DispatchHandler - registering 0xbb2c72394b1ab9f8e6c5459001105f177f2fc3ea for 0xbb2c72394b1ab9f8e6c5459001105f177f2fc3ea with [6]
21:56:56.418 [main] DEBUG net.tomp2p.rpc.DispatchHandler - registering 0xbb2c72394b1ab9f8e6c5459001105f177f2fc3ea for 0xbb2c72394b1ab9f8e6c5459001105f177f2fc3ea with [5]
21:56:56.422 [main] DEBUG net.tomp2p.rpc.DispatchHandler - registering 0xbb2c72394b1ab9f8e6c5459001105f177f2fc3ea for 0xbb2c72394b1ab9f8e6c5459001105f177f2fc3ea with [7]
21:56:56.424 [main] DEBUG net.tomp2p.rpc.DispatchHandler - registering 0xbb2c72394b1ab9f8e6c5459001105f177f2fc3ea for 0xbb2c72394b1ab9f8e6c5459001105f177f2fc3ea with [12]
21:56:56.431 [main] DEBUG net.tomp2p.rpc.DispatchHandler - registering 0xbb2c72394b1ab9f8e6c5459001105f177f2fc3ea for 0xbb2c72394b1ab9f8e6c5459001105f177f2fc3ea with [25]
21:56:56.474 [main] DEBUG net.tomp2p.rpc.DispatchHandler - registering 0xbb2c72394b1ab9f8e6c5459001105f177f2fc3ea for 0xbb2c72394b1ab9f8e6c5459001105f177f2fc3ea with [1, 2, 3, 4, 11, 14, 13, 16, 19, 20, 23, 26]
21:56:56.505 [main] DEBUG net.tomp2p.connection.Reservation - Reservation UDP=2, TCP=4
21:56:56.599 [pool-2-thread-1] DEBUG net.tomp2p.dht.DistributedHashTable - found direct hits for get: []
21:56:56.658 [pool-2-thread-1] DEBUG net.tomp2p.utils.ConcurrentCacheMap - get not found: 0xbb2c72394b1ab9f8e6c5459001105f177f2fc3ea
21:56:56.675 [pool-2-thread-1] DEBUG net.tomp2p.connection.Sender - Handle message that is intended for the sender itself msgid=603113936,t=REQUEST_1,c=GET,tcp,s=paddr[0xbb2c72394b1ab9f8e6c5459001105f177f2fc3ea[/192.168.1.147,4002]]/relay(false)/slow(false),r=paddr[0xbb2c72394b1ab9f8e6c5459001105f177f2fc3ea[/192.168.1.147,4002]]/relay(false)/slow(false)
21:56:56.681 [pool-2-thread-1] DEBUG net.tomp2p.peers.PeerMap - peer paddr[0xbb2c72394b1ab9f8e6c5459001105f177f2fc3ea[/192.168.1.147,4002]]/relay(false)/slow(false) is online reporter was paddr[0xbb2c72394b1ab9f8e6c5459001105f177f2fc3ea[/192.168.1.147,4002]]/relay(false)/slow(false)
21:56:56.687 [pool-2-thread-1] DEBUG net.tomp2p.dht.StorageRPC - handleGet msgid=603113936,t=REQUEST_1,c=GET,tcp,s=paddr[0xbb2c72394b1ab9f8e6c5459001105f177f2fc3ea[/192.168.1.147,4002]]/relay(false)/slow(false),r=paddr[0xbb2c72394b1ab9f8e6c5459001105f177f2fc3ea[/192.168.1.147,4002]]/relay(false)/slow(false)
21:56:56.694 [pool-2-thread-1] DEBUG net.tomp2p.dht.StorageRPC - response for storage request: msgid=603113936,t=OK,c=GET,tcp,s=paddr[0xbb2c72394b1ab9f8e6c5459001105f177f2fc3ea[/192.168.1.147,4002]]/relay(false)/slow(false),r=paddr[0xbb2c72394b1ab9f8e6c5459001105f177f2fc3ea[/192.168.1.147,4002]]/relay(false)/slow(false)
21:56:56.695 [pool-2-thread-1] DEBUG net.tomp2p.dht.DistributedHashTable - fork/join status: 1/1 (3)
21:56:56.704 [pool-2-thread-1] DEBUG net.tomp2p.dht.DistributedHashTable - set data from paddr[0xbb2c72394b1ab9f8e6c5459001105f177f2fc3ea[/192.168.1.147,4002]]/relay(false)/slow(false)
Exception in thread "main" java.util.NoSuchElementException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1431)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1458)
	at com.openmarket.ExampleDNS.get(ExampleDNS.java:59)
	at com.openmarket.ExampleDNS.main(ExampleDNS.java:51)
```

**Comment by tchoulihan** [comment]
That did it. Thanks Thom!
